src/lib.rs
Delegate to the `[T]` impls of these traits, like `Vec<T>` does.
=> Simplify Hash, Ord, and PartialOrd impls

src/lib.rs
Implementation copied from the standard library.  The additional changes are to make the doctest work.
=> Implement `retain`, `dedup`, `dedup_by`, and `dedup_by_key`

src/lib.rs
drop_in_place already does a needs_drop check (std::Vec doesn't bother).
=> remove unnecessary needs_drop checks

src/lib.rs
This is copied from https://doc.rust-lang.org/src/std/io/impls.rs.html#257 and lets me do
```
write!(&mut my_thin_vec, "hello {}", "world");
```
=> Implement the trait Write for ThinVec<u8>

Cargo.toml, src/lib.rs
* hopefully fixes auto bit handling on big endian platforms
* fixes seeming oversight in auto array reallocation
* revamps documentation to discuss gecko-ffi feature
* updates to rust 2018
=> gecko-ffi overhaul

src/lib.rs
=> Ensure `Header::data<T>` returns a pointer properly aligned for `T`

Cargo.toml
Just was poking at the documentation and wanted to fix the repo link
=> Fix typo in repo url

src/lib.rs
`ThinVec<T>` is just `Vec<T>` except that it stores `len` and `cap` inline, so I don't see any reason why it cannot be `Send` and `Sync`.
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>
=> Impl `Send` and `Sync` for `ThinVec<T>`

src/lib.rs
I've been running `MIRIFLAGS="-Zmiri-tag-raw-pointers" cargo miri test` on a number of crates, and I recently came across this one. Here's what I found:
* A `&Header` cannot be used to get a useful pointer to data beyond it, because the pointer from the as-cast of the `&Header` only has provenance over the `Header`.
* After a `set_len` call that decreases the length, it is invalid to create a slice then try to `get_unchecked` into the region between the old and new length, because the reference in the slice that the `ThinVec` now `Deref`s to does not have provenance over that region. Alternatively, this is UB because the docs stipulate that you're not allowed to use `get_unchecked` to index out of bounds.
* Misaligned data pointers were produced when the `gecko-ffi` feature was enabled …
=> Fix provenance UB and alignment UB

src/lib.rs
=> Allow `set_len(0)` on an empty `ThinVec`.

src/lib.rs
Some small performance wins I found while integrating `ThinVec` into rustc.
=> Optimize `clone` and `extend`

Cargo.toml, src/lib.rs
This PR adds serialization via `serde::Serialize` and `serde::Deserialize`.
The de-serializer is guarded against malicious size hints, in the exact same manner as `serde`'s `Deserialize` `impl` for `Vec`.
The implementation was modeled off of `arrayvec`.
=> Add serde support (optional `serde` feature).

src/lib.rs
These commits optimize several operations better for the case where the `ThinVec` is empty. This is a common case for my use case of interest (in `rustc`) and is likely a pretty common case for `ThinVec` in general. (More so than `Vec`, for example.) It does slightly pessimize the non-empty cases, but only to the tune of a single branch per operation, which is hopefully acceptable.
=> Optimize more for the empty case

.github/workflows/rust.yml, src/lib.rs
By simply ignoring the doctests when that feature is enabled.
The only downside of this is that if you run `cargo doc
--features=gecko-ffi` you'll get little annotations on the examples in
the generated docs saying "This example is not tested". But it seems
unlikely anyone will be running that command.
The commit also enables CI testing of `gecko-ffi`.
=> Fix `cargo test --features=gecko-ffi`.

src/lib.rs
This is almost entirely copy-pasting from std. I also fleshed out a bunch of docs in Drain. This is a yakshave to prep for adding splice support.
=> Add a crapton of missing trait impls and docs

src/lib.rs
The impl is a copy-paste of the one in std. Seemingly no significant modifications
were necessary.
This is based on top of #40
=> Add splice to thin_vec

src/lib.rs
It was removed in 6e511609cd8eb10f70d12da8e2b99581ec318435 which seems to have been an accident.
Fixes #42
=> Add missing unsafe block in ThinVec::is_singleton with gecko-ffi

src/lib.rs
I saw that `len` didn't get inlined in `rustc` so these probably could use some `#[inline]` attributes.
=> Add inline attributes on Header functions

src/lib.rs
I was mentally applying the rule that capacity can never exceed isize::MAX as a precondition BUT this is the code necessary for enforcing that! In fixing this I broke the fact that this code was subtly relying on that overflow to allow usize::MAX ZSTs to be allocated (by only allocating space for the header). ZSTs previously actually worked fine, as the garbage overflowed value was always wiped out by multiplying by 0 to get the array size. Now we need to handle it more explicitly.
(also a driveby explanation for why #42 happened)
=> Handle overflows in capacities more

src/lib.rs
The assertion is to uphold safety invariants, but the method is unsafe. Changing this to a debug assertion allows the compiler to omit the check, as the caller is asserting that it is true.
=> Change assertion to debug assertion

src/lib.rs
This is useful since LLVM can omit the destructor if it knows `!has_capacity()`. It can be used to make https://github.com/rust-lang/rust/pull/108359 cleaner.
=> Add `has_capacity` as a proxy for `is_singleton`

.github/workflows/rust.yml, Cargo.toml, src/lib.rs
This is a rebased and amended version of #49
=> Make thin-vec compatible with no_std

.github/workflows/rust.yml, Cargo.toml, RELEASES.md, src/lib.rs
Now that [malloc_size_of](https://github.com/servo/malloc_size_of) is published to crates.io we are moving the trait implementations of [MallocSizeOf](https://docs.rs/malloc_size_of/latest/malloc_size_of/trait.MallocSizeOf.html) and related traits into the crates that define the types. This will avoid the situation where depending on `malloc_size_of` pulls in a large number of dependencies, and is needed for ongoing use of this crate by the Servo and Gecko projects.
This PR adds the implementation of `MallocSizeOf` to the `thin-vec` crate.
=> Implement `MallocSizeOf` for `thin-vec`

src/lib.rs
This removes a couple instructions from `ThinVec::push` and probably other methods as previously each `expect` was getting it's own jump to `call expect_failed` whereas with this they can all simply jump to call `capacity_overflow`. This also leads to the inlining of `header_with_capacity` into `ThinVec::push`, which was previously an outlined call.
I can't find any benchmarks in the repo to test against, but the increased inlining with a smaller method sounds like a good thing.
=> Move capacity overflow panic to own cold function

src/lib.rs
Since we only ever `ptr::read` from the references returned by `self.iter.next()`, they can just as well be shared references as mutable ones, so we use `Iter` instead of `IterMut` to get covariance. `*mut ThinVec<T>` becomes `NonNull<ThinVec<T>>` for covariance also.
=> Make `Drain<'_, T>` covariant in `T`.

src/lib.rs
On i686, the u64 test sometimes fails because the required alignment is
4-bytes, not 8-bytes.
Closes #56
Co-authored-by: Peter Michael Green <plugwash@debian.org>
=> Use core::mem::align_of to determine proper type aligment

.github/workflows/rust.yml, src/lib.rs
Turns out we can test the gecko-ffi mode in this crate, that's nice.
AutoThinVec hits some of the stacked borrows limitations, so test with
tree borrows in this mode.
=> Add some tests for auto_thin_vec.

src/lib.rs
Reviewed upstream in https://bugzil.la/1984102
=> gecko: Keep the auto-bit across relocations.
